config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }

  root 'posts#index'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts, only:[:new, :create, :index, :show, :destroy] do
    resources :photos, only:[:create]
    resources :likes, only:[:create, :destroy]
  end


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
    
    # user_idとpost_idの組み合わせが重複していないことを検証
    # ユーザーは１post（記事）に対して１like（いいね）しかできない
    validates :user_id, uniqueness: { scope: :post_id }


    def liked_by(user)
        # user_idとpost_idが一致するlikeを検索する
        Like.find_by(user_id: user.id, post_id: id)
    end
end

app/models/photo.rb
class Photo < ApplicationRecord

    # postテーブルと１対多の関係を示す
    belongs_to :post
    # イメージカラムに対して値が空ではないということ確かめるバリデーション
    validates :image, presence: true
    # Uploaderをphotoモデルのイメージカラムに紐付け
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
    # userテーブルと１対多の関係
    belongs_to :user

    # photoテーブルと１対多の関係
    # postテーブルが削除されると必然とphotoテーブルも削除される
    has_many :photos, dependent: :destroy

    has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy

    # 親子関係のある関連モデル(今回でいうとPostモデルとPhotoモデル）で、親から子を作成したり保存するときに使用
    # 投稿する際にPostモデルの子に値するPhotoモデルを通して、photosテーブルに写真を保存します
    accepts_nested_attributes_for :photos
end

app/models/user.rb
class User < ApplicationRecord

  # オブジェクトが削除されるときに、関連付けられたオブジェクトのdestroyメソッドが実行されます。
  # つまり今回で言うと、ユーザーが削除されたら、そのユーザーに紐づく投稿も削除します。
  has_many :posts, dependent: :destroy

  has_many :likes

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  def update_without_current_password(params, *options)
    # if フォームのパスワード欄が空欄？
    #   　　　パラメータのパスワード情報を削除
    #   　　　パラメータのパスワード確認情報を削除
    #   　　　パラメータの現在のパスワード情報を削除
    #   　　　結果=self.update(名前情報,メールアドレス情報)
    #   else #(フォームのパスワード欄に入力が有りの場合)
    #   　　　current_password=パラメータの現在のパスワード情報
    #   　　　result= if 現在のパスワードが正しい？
    #           結果=self.update(名前情報,メールアドレス情報,パスワード情報,パスワード確認情報)
    #        else#(フォームの現在のパスワード欄に入力誤りの場合)
    #           更新中の値（名前情報,メールアドレス情報,パスワード情報,パスワード確認情報）をフォームの各欄に戻す
    #   　　　　　現在のパスワードがエラーになった理由を返す。
    #   　　　end
    #   end
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
      params.delete(:current_password)
      result = update(params, *options)
    else
      current_password = params.delete(:current_password)
      result = if valid_password?(current_password)
        update(params, *options)
      else
        assign_attributes(params, *options)
        valid?
        errors.add(:current_password, current_password.blank? ? :blank : :invalid)
        false
      end
    end

    clean_up_passwords
    result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    # サインイン済みユーザーのみにアクセス許可
    before_action :authenticate_user!

    def create
        @like = current_user.likes.build(like_params)
        @post = @like.post
        if @like.save
          respond_to :js
        end
    end

    def destroy
        @like = Like.find_by(id: params[:id])
        @post = @like.post
        if @like.destroy
          respond_to :js
        end
      end
    
    private
    # paramsとは送られてきたリクエスト情報をひとまとめにしたものです。
    # permitで変更を加えられるキーを指定します。今回の場合、post_idキーを指定しています。
    # いいねを押したときに、どの投稿にいいねを押したのかpost_idの情報を変更できるように指定しています
    def like_params
        params.permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    # :authenticate_user!はdeviseが用意しているヘルパー
    # サインインしていない状態でnewアクションやcreateアクションを実行しようとすると、サインインページにリダイレクト
    before_action :authenticate_user!

    # @post = Post.find_by(id: params[:id])をshowとdestroyに最初に適用
    before_action :set_post, only: %i(show destroy create)

    def new
        @post = Post.new
        @post.photos.build
    end

    def create
        @post = Post.new(post_params)

        # present?はnilまたは空のオブジェクト（例えば空の配列）でなければtrueを返します。
        # なので@post.photosが空のオブジェクトでなければtrue、それ以外ならfalse
        if @post.photos.present?
          @post.save
          redirect_to root_path
          flash[:notice] = "投稿が保存されました"
        else
          redirect_to root_path
          flash[:alert] = "投稿に失敗しました"
        end
    end

    def index
      # includesメソッドを使うことで必要な情報のみを拾ってくるため処理が早くなる
      # 今回の場合では:photosと:userのみ拾ってくる。
      @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
    end

    def show
      @post = Post.find_by(id: params[:id])
    end

    def destroy
      @post = Post.find_by(id: params[:id])

      # 投稿したユーザーと現在サインインしているユーザーが等しければ、真を返す条件式
      if @post.user == current_user
        # @post.destroyが真だったら、「投稿が削除されました」というフラッシュメッセージを表示
        flash[:notice] = "投稿が削除されました" if @post.destroy
      else
        flash[:alert] = "投稿の削除に失敗しました"
      end
      redirect_to root_path
    end
    
    private
        def post_params
            # paramsとは送られてきたリクエスト情報をひとまとめにしたものです。
            # requireで受け取る値のキーを設定します。
            # permitで変更を加えられるキーを指定します。今回の場合、captionキーとimageキーを指定しています。
            # mergeメソッドは2つのハッシュを統合するメソッドです。今回は誰が投稿したかという情報が必要なためuser_idの情報を統合しています。
          params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
        end

        def set_post
          @post = Post.find_by(id: params[:id])
        end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    protected
  
    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end

    def after_update_path_for(resource)
        user_path(resource)
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
        # user.profile_photoカラムがnilでなければ、user.profile_photoを返す
        return user.profile_photo unless user.profile_photo.nil?
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        "https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/15782/2da91636-af73-4eed-91cd-320a0399609c.jpg"
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © Yuugram
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <%= link_to image_tag("/assets/logo.png", class: "navbar__brand navbar__mainLogo"), root_path %>
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
      </li>
      <li class="nav-item">
        <%= link_to image_tag("/assets/parts3.png", class: "nav-link"), user_path(current_user) %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yuugram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%# ログインしていないユーザーにはNavbarを表示しないようにしていきます。 %>
  <%= render 'layouts/navbar' if current_user %>
  
  <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
  <% end %>
    <%= yield %>

  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %> <%#ユーザーがログインしているかどうか判定 rails devise ヘルパーメソッドで検索 %>
    <%= button_to 'サインアウト', destroy_user_session_path, method: :delete %>
<% end %>   

<p>このページは仮のトップページです。</p>
<%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/index.html.erb
<%# 一覧表示 %>
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

<%# 削除機能 %>
        <%# 現在サインインしているユーザーと投稿したユーザーが等しければ、リンクを表示させる条件式 %>
        <% if post.user_id == current_user.id %>
            <%= button_to post_path(post), data: { "turbo-method": :delete }, class: "ml-auto mx-0 my-auto" do %>
            <%# <%= button_to 'Delete', post, :method => :delete  %> 
              <%= image_tag '/assets/parts9.png' %>
              
            <% end %>
          <% end %>

        </div>
         <%# mediumは「carrierwaveとMiniMagickの導入」でphoto_uploader.rbに追記したバージョンです %>
        <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>

        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>

        <div class="card-body">
          <div class="row parts">
          <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" do %>
                  <%= image_tag '/assets/parts7.png' %>
                
              <% end %>
              <% else %>
                <%= link_to post_likes_path(post), method: :POST, remote: true, class: "loved hide-text" do %>
                  <%= image_tag '/assets/parts7.png' %>
                
                <% end %>

              <% end %>
            </div>
           
            <%= link_to "", "#", class: "comment" %>
          </div>

     
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "posts/like_text", { likes: post.likes } %>
          </div>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
           <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
            <hr>
            <div class="row parts">
              <form action="#" class="w-100">
                <div>
                  <textarea class="form-control comment-input border-0" placeholder="コメント..." rows="1"></textarea>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
            </div>
          </div>
          <div class="mb-3">
            <%# fields_forを使うことで、子モデル（今回でいうとPhotoモデル）に変更を加えることができる %>
            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image %>
            <% end %>

          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>

            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), data: { "turbo-method": :delete }, class: "ml-auto mx-0 my-auto" do %>
                <%= image_tag '/assets/parts9.png' %>
                
              <% end %>
            <% end %>   
          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
            </div>
          </div>
        </div>
        <div class="row parts">
        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-4 text-center">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-8">
      <div class="row">
        <h1><%= @user.name %></h1>

        <% if @user == current_user %>
            <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
            <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">x</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @user == current_user %>
        <div class="row">
          <p>
            <%= @user.email %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>